FROM debian:jessie
# FROM scratch

ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

### stuff stuff stuff

RUN apt-get update && apt-get upgrade -y && apt-get install -qq -y --no-install-recommends \
        btrfs-tools \
        curl \
        gcc \
        git \
        golang \
        libdevmapper-dev \
        libsqlite3-dev \
        \
        ca-certificates \
        e2fsprogs \
        iptables \
        procps \
        xfsprogs \
        xz-utils \
        \
        aufs-tools
    # && rm -rf /var/lib/apt/lists/*
