# fctwallet:
  # build: Dockerfile_fctwallet
  # links:
      # - factom_golang

factomd:
  image: factom_factomd
  # links:
      # - factom_golang
  volumes:
      - ./factomdata:/factomd/.factom
  ports:
      - "127.0.0.1:8384:8384"
      - "0.0.0.0:8108:8108"
  command: factomdata:/factomd
