# https://github.com/FactomProject/factomd.git

FROM factom_golang

ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

ENV USER factom
ENV HOME /factom
ENV PATH $PATH:/usr/local/go/bin
ENV GOPATH $HOME
ENV GOROOT /usr/local/go

RUN mkdir -p $HOME/.factom
RUN useradd -m -d $HOME $USER

RUN apt-get update \
    && apt-get install -y -qq git mercurial wget \
    && go get -v github.com/FactomProject/FactomCode/factomd

RUN rm -rf /var/lib/apt/lists/* # clean up repos
RUN chown -R $USER:$USER $HOME

ADD factomd.conf $HOME/.factom/factomd.conf

# EXPOSE 8088 # api
# EXPOSE 8089 # fctwallet?
# EXPOSE 8090 # control panel
# EXPOSE 8108 # p2p network port (only outgoing)
# EXPOSE 8384 # rpc

USER $USER

WORKDIR $HOME

ENV GOPATH $HOME
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

# VOLUME ["${HOME}/.factom"] # formerly set via makefile/docker-compose

CMD ./bin/factomd
