# https://storage.googleapis.com/golang/go1.4.1.linux-amd64.tar.gz
# https://storage.googleapis.com/golang/go1.5.3.linux-amd64.tar.gz

FROM factom_base
# FROM buildpack-deps:jessie-scm

# gcc for cgo
RUN apt-get update && apt-get install -y --no-install-recommends \
        g++ \
        gcc \
        libc6-dev \
        make
    # && rm -rf /var/lib/apt/lists/*

# ENV GOLANG_VERSION 1.5.3
ENV GOLANG_VERSION 1.4.1
ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 68170d5d48fc317155e69d2b55e4c09878433462ddb77d7900db6590ce2bef49

RUN curl -fsSL "$GOLANG_DOWNLOAD_URL" -o golang.tar.gz \
    && echo "$GOLANG_DOWNLOAD_SHA256  golang.tar.gz" | sha256sum -c - \
    && tar -C /usr/local -xzf golang.tar.gz \
    && rm golang.tar.gz

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 755 "$GOPATH"
WORKDIR $GOPATH

# COPY go-wrapper /usr/local/bin/
