all: build

help:
	@echo ""
	@echo "-- Help Menu"
	@echo ""
	@echo "   1. make build       - build the factomd image"
	@echo "   2. make quickstart  - start factomd"
	@echo "   3. make stop        - stop factomd"
	@echo "   4. make logs        - view logs"
	@echo "   5. make purge       - stop and remove the container"

build:
	@docker build --tag=${USER}/factomd .

release:
	@docker build --tag=${USER}/factomd:$(shell cat VERSION) .

quickstart:
	@echo "Starting factomd..."
	@docker run --name=factomd-demo -d -p 10080:80 \
		-v /var/run/docker.sock:/run/docker.sock \
		-v $(shell which docker):/bin/docker \
		${USER}/factomd:latest >/dev/null
	@echo "Please be patient. This could take a while..."
	@echo "factomd will be available at http://localhost:10080"
	@echo "Type 'make logs' for the logs"

stop:
	@echo "Stopping factomd..."
	@docker stop factomd-demo >/dev/null

purge: stop
	@echo "Removing stopped container..."
	@docker rm factomd-demo >/dev/null

logs:
	@docker logs -f factomd-demo
